### ISSUE TITLE
SyntaxError: Unexpected end of JSON input after token input

### ISSUE THREAD

**Issue by rrambaldi** [albertosantini/argo#10]
Hello, I just installed argo-trading via npm as described on  a VPS I own. I executed argo-trading and get connected to the machine at port 8000. page displays and I enter the token for the practice environment, but the page stucks "loading" and on the console I see the error: SyntaxError: Unexpected end of JSON input

I already tested the token by interfacing directly to Oanda APIs and it works fine.
I use npm-3.10.8 on a CentOS 7.2 linux box.

thanks so far for the support

**Comment by albertosantini** [comment]
Thanks for the feedback. 

At the moment I am out of town: I will check it better when I come back. 

That error is irrelevant, if you mean the console log of the browser: a few times, in practice market, initial ticks are wrong. Indeed I removed that message in the master version. 

After inserting the token, the token dialog is hidden: quotes list and EUR_USD candle chart are displayed.

Please, check Node.js console for any error (the terminal) and double check if you are using the latest node version, at least the 6.x, with the command "node -v".

**Comment by albertosantini** [comment]
Another suggestion. 

Don't forget Argo 4.x works with v20 accounts and Argo 3.x with legacy ones.

**Comment by rrambaldi** [comment]
I found the issue: token was valid but no account was attached to it (!)
my tests were fine because by mistake I was using sandbox and v1 api.
I created a new practice account and everything works fine (almost, I have issues now with streaming...).

anyway I patched your code in order to

1) avoid such issue by rising and error that accounts response is empty
2) add more logging info in reserver apiProcess error handling.

I'm new to github, I do not know how to submit those patches please let me know if you are interested and how I can push it to you

thanks so far.

**Comment by albertosantini** [comment]
Thanks for the details and the effort.

About the patch, if it is convenient for you, you can create a GitHub Pull Request.
Otherwise you can paste here the difference with the command `git diff`.
