### ISSUE TITLE
TradingView?

### ISSUE THREAD

**Issue by Worthy7** [albertosantini/argo#12]
Hi there, this project looks a little slim, but looks promising. I was wondering if you could contact founders@tradingview.com to see if they would allow you some kind of solution that you could add to this project. This will allow a very similar experience to TradingView itself, but with much more and unrestricted broker integration.

**Comment by albertosantini** [comment]
Thanks for the feedback.

The main aim of Argo is providing a sort of platform to execute trading strategies.

Bottom line, the plugins are more important than the user interface.
The web part is there only like a dashboard for the plugins activity.

Really the official [Oanda web app](https://trade.oanda.com/) should fill the professional trading requirements in terms of charts, analysis and whatever about the usual trading workflow.

Argo architecture is open in terms of adding new data providers, brokers and plugins.

Feel free to contribute to contribute to the project. :)

**Comment by Worthy7** [comment]
I have person issues with their web app, which is exactly why I'm looking at the project. But what I like the most was using TradingView's right click=> order button on the chart, which I don't think I'll be able to easily reproduce. Anyway, Thanks for the reply.

**Comment by albertosantini** [comment]
I understand and thanks to consider Argo.

There are a lot of of details we may add to the user interface to support the trading habits of every customer.

But this kind of details or features, user interface related, as explained, is not the main scope of the project, even if I am open to merge any contribution.

**Comment by Worthy7** [comment]
Understood - thanks
