### ISSUE TITLE
Electron

### ISSUE THREAD

**Issue by liborty** [albertosantini/argo#13]
The stand alone app will not run without electron but electron fails to install on my linux mint 32bit i686 architecture (complains about not being able to make some directories, even when npm install -g electron is run as a superuser).

**Comment by albertosantini** [comment]
Thanks for the feedback.

If `electron` dep is not installed in your environment, your chance is opening an issue in that project, providing the details required.

Here I cannot help you.

In the meantime you may use `argo` as web app.
