### ISSUE TITLE
Could you please support stock exchange?

### ISSUE THREAD

**Issue by royburns** [albertosantini/argo#14]
thanks for all of you
i notice that this application just for Forex exchange
could you please support stock exchange?

**Comment by albertosantini** [comment]
Thanks for feedback. Good question.

Firstly the application supports OANDA broker, hence Forex market.

The main use case of the application is providing a platform to play with trading strategies, not creating a user interface for a user. Bottom line the charts part is useless. at least for me.
The application cannot compete with other professional offer. Just the default application provided by OANDA is very good in terms of charts and graph.

Due the focus on strategies, I need a market opened 24H and very liquid.

Furthermore supporting the stock exchange market, you need to find a free broker with no delay and also with historical prices. Then you need to create the adapter for that broker and integrate it in the application. I suppose you know the kind of the effort.

Feel free to offer a proposal and, finally, to contribute.

**Comment by royburns** [comment]
Got it
thanks for your reply :)
