### ISSUE TITLE
No plugins shown!

### ISSUE THREAD

**Issue by tarmo1979** [albertosantini/argo#18]
If I login to http://localhost:8000 and enable plugins,
then I close browser and relogin to http://localhost:8000, 
then it shows No plugins, but server and plugins are still running ok in background.
<img width="959" alt="Screenshot 2019-08-26 21 00 26" src="https://user-images.githubusercontent.com/5405691/63711631-8c60db80-c844-11e9-9442-a46861fc9ced.png">

**Comment by albertosantini** [comment]
Thanks for the feedback. I can reproduce it.

I give a look to fix it.

**Comment by albertosantini** [comment]
Published `v6.2.5`.

Hope that helps.

I tested it and it works.

You need to wait for the streaming is initialized and you can see the plugins tab updated with the latest plugins status.

**Comment by tarmo1979** [comment]
Thanks

Tarmo
