### ISSUE TITLE
Error when stop loss and take profit are expressed in pips

### ISSUE THREAD

**Issue by sundayoyeniyi** [albertosantini/argo#2]
Hi Alberto,

When you open order dialog and choose vm.measure = pips the api returns error because of in-appropriate stop or take profit.

I noticed that in client/app/charts/order-dialog.js you have initialised vm.measure = "price", however, in the template this value can be either "price" or "pips".

I think that order-dialog.js needs to be re-written around line 109 to 123 or around line 55 to 67 such that when vm.measure = "pips" then take profit, stop loss and trailing stop are calculated in price and send to putOrder instead of in pips.  The calculation will be slightly different for JPY crosses.

Would you do this or you want me to send you a PR for this?

Thanks

SO.

**Comment by albertosantini** [comment]
Are you sure you have the latest version (1.8.3)?
Indeed those parts of code you mention have been rewritten.

I filled an order, for instance USD_JPY with PIPS mode, and it was executed correctly.

**Comment by sundayoyeniyi** [comment]
Hi Alberto,

Yes, I am using version 1.8.3 

See the fork that I cloned here: https://github.com/sundayoyeniyi/argo/blob/master/package.json

Any thoughts?

Thanks

SO

**Comment by albertosantini** [comment]
Please, shall you tell me the steps to reproduce the error?

In my test case, I select USD_JPY, open dialog order, check PIPS and press submit.

Be aware USD_JPY should be in the quote list, otherwise price is undefined.
I am sure I should add a check there, but if you await for a USD_JPY tick, the order in terms of PIPS should be filled correctly.

**Comment by sundayoyeniyi** [comment]
Hi Alberto,

Open an order dialog and fill the content using the screen shot attached.  The second screen shot is what I got when I clicked submit.

Order-dialog input
![capture-1](https://cloud.githubusercontent.com/assets/3162619/7062648/4d8dcfb2-de97-11e4-8199-505c2ddc9619.PNG)

Toast response
![capture-2](https://cloud.githubusercontent.com/assets/3162619/7062656/60c63ea2-de97-11e4-96c8-af008d4f29c2.png)

I hope this helps

SO.

**Comment by albertosantini** [comment]
Got it. Thanks.
Working on it.

**Comment by albertosantini** [comment]
I should be fixed.

Before creating a new release, I wait for your feedback. Thanks.

**Comment by albertosantini** [comment]
Too fast. :)
I use the default values and not the modified ones.

Ok, working on it.

**Comment by albertosantini** [comment]
I hope this latest commit fixes the issue.

**Comment by sundayoyeniyi** [comment]
Hi Alberto,

Thanks for sorting out.

I'll pull later today and let you know.  However, I have briefly reviewed the changes to order-dialog.js and the template order-dialog.html.  It looks to me that the update will work for non - JPY crosses but any instrument that includes JPY won't be correct.

I'll double check later and come back to you.

Best wishes

SO.

**Comment by albertosantini** [comment]
I compared the orders (for USD_JPY) filled with fxTrade and Argo and it seems they are correct.
Furthermore the calculation is aware about pip (`vm.step`) per instrument.

Waiting for your tests. Thanks a lot!

**Comment by albertosantini** [comment]
In the next hours I prepare release 1.8.4.
I did a few tests more about filling an order in PIPS mode and it seems it is a green light.

**Comment by albertosantini** [comment]
1.8.4 published.

As usual feel free to open a new issue, change request o question. Thanks!

**Comment by sundayoyeniyi** [comment]
Hi Alberto,

Yes, this was sorted out and I did tried it out earlier.  I will pull the new release.

Best wishes

SO.
