### ISSUE TITLE
Charts does not updated tick-by-tick.

### ISSUE THREAD

**Issue by khayong** [albertosantini/argo#20]

**Comment by albertosantini** [comment]
Thanks for the feedback.

Well, for instance, if you choose a chart with granularity S5, I see the last candle bar (the most right one) updated tick-by-tick and every 5 seconds is created a new bar, scrolling.

So I cannot reproduce it. 

Do you mean anything different I described above?

**Comment by khayong** [comment]
Sorry for my overlooked. Thanks!
