### ISSUE TITLE
Interest in contributing to this project

### ISSUE THREAD

**Issue by sundayoyeniyi** [albertosantini/argo#3]
Hi Alberto,

I really like this project and will like to learn from it by taking the time to contribute to it.

What aspects of this project do you think will benefit from contribution from others?

Happy if you let me know.

Cheers

SO

**Comment by albertosantini** [comment]
Dear @sundayoyeniyi,

thanks for interesting in the project.

Generally speaking we are at 1.9.x release: the basic features are stable, there are docs and tests. The app is usable. In the meantime I have been developing the framework for trading strategy plugins, to be released in 2.x release.

A few (casual) details about next steps.

- 1.9.x - Improving UI details
    - Tab views: add blue or orange background for long or short row (add or reuse a directive, see in components folder for an example).
    - (Tab views: showing the table-like, the header creates a (ugly) scrolling effect because it is outside of md-content, see any tab partial. Waiting for table widget in Material post 1.0 for a final solution.)
    - Quotes view: the order should be fixed and not in order of updating. :)
    - (Quotes view: getting the initial snapshot of the rates provided by the streaming to avoid blank view when there are no updates for long time.).
    - argo.js.org: add a short video (30secs on YouTube with CamStudio) to show the features.

- 2.x - Plugins
    - Add service locator pattern (register) for trading strategies based on Seneca microservices framework.
    - Add Strategies view, listing the strategies to activate (with instrument, granularity, etc. params).
    - Add argo-trading-plugin-seed (new repo), the skeleton for a trading strategy plugin based on Seneca microservices framework.
    - Add main technical indicators (available in the plugins): EMA, SMA, RSI, MACD (see askmike/gekko repo).
    - Add docs and tests.

- 3.x - Mobile support and charts enhancement
    - Improve support for mobile devices.
    - Add code coverage (gotwarlost/istanbul).
    - Add trade and order markers to the chart.
    - Add different kind of chart (candlestick, for instance).
    - (Add graphs to the chart).

- 4.x - Improving distribution and installation process
    - Explore the opportunity to create an executable (atom/electron).


Please, feel free to add any change request in terms of features or priorities.
I look forward to hearing from you.

**Comment by albertosantini** [comment]
Switched to [flic](https://github.com/nkcmr/flic) package as plugin framework.

**Comment by albertosantini** [comment]
Feel free to add specific issues.
In the next days I release a major release providing plugin support.
