### ISSUE TITLE
Problem with running after sucessfull installation

### ISSUE THREAD

**Issue by BenGosub** [albertosantini/argo#4]
After sucessfully installing argo-trading I run:

"argo-trading"

And get a response:

"env: node\r: No such file or directory"
Any idea how to fix this?
I have Mac OS X Lion (10.7.5)

**Comment by albertosantini** [comment]
I think there is a problem with line format (dos vs. unix).
My fault.

In a few days, I think on Monday, I release a new major version.
In the meantime, there are two workarounds:

 - clone the repo and execute `npm start` or
 - open and save in unix format  the start script `argo/bin/argo-trading`, located in your global `node_modules`

**Comment by BenGosub** [comment]
Thank you for your answer, I'll try to fix this, if I don't succeed then I can wait for the new release.

**Comment by albertosantini** [comment]
If you clone the repo, in master I fixed the issue. 
(I hope). :)
