### ISSUE TITLE
Problems on Mac

### ISSUE THREAD

**Issue by scrumit** [albertosantini/argo#5]
I had a small problem starting Argo on Mac. I got error "env: node\r: No such file or directory"

The problem appears to be dos line endings on the javascript file.

The solution for Mac users is to run dos2unix on the argo-trading file in /usr/local/..../bin/

More details are [here](https://github.com/gorangajic/workmode/issues/1)

This may apply to Unix installations as well.

**Comment by albertosantini** [comment]
I thought to have fixed it in #4.

I publish a new release in a few hours.

**Comment by albertosantini** [comment]
Published 2.6.0. 

Thanks for the feedback.
