### ISSUE TITLE
Does not start on Mac

### ISSUE THREAD

**Issue by pranasblk** [albertosantini/argo#7]
$ npm install -g argo-trading
$ argo-trading
env: node\r: No such file or directory

I'm a beginner in Angular and would like to learn from you projects, some guidelines to start the system?

**Comment by albertosantini** [comment]
Thanks for the feedback.

Ops end-of-line issue. :)

In the meantime you may execute `npm start`.
To start the electron implementation `npm run electron`.

Generally speaking, you may give a look at `scripts` property in `package.json`.

(You may fix it - you need to open and to save those files in `bin` folder with unix end-of-line - and contribute a PR).

**Comment by albertosantini** [comment]
The issue is fixed next time a new version will be published, due to https://github.com/albertosantini/argo/commit/86a932d2447e374bcd2f9fd15050ea1017b03c6c.

**Comment by albertosantini** [comment]
In the meantime, you may use the commands suggested in the previous post or simply you may save `argo-trading` script with the correct end-of-line.
