### ISSUE TITLE
Error messages upon launching on GNU/Linux

### ISSUE THREAD

**Issue by dariox86** [albertosantini/argo#8]
After installing with "npm install -g argo-trading", the application won't work because /usr/bin/algo-trading has the problem with Windows termination character. I didn't check /usr/bin/algo-trading-standalone, but at this point I have reason to believe it may be affected as well. After manually fixing the problem with the script, I get the following error message when launching algo-trading:
`[dario@quadcore ~]$ argo-trading
module.js:442
    throw err;
    ^

Error: Cannot find module '../src/server/app'
    at Function.Module._resolveFilename (module.js:440:15)
    at Function.Module._load (module.js:388:25)
    at Module.require (module.js:468:17)
    at require (internal/module.js:20:19)
    at Object.<anonymous> (/usr/bin/argo-trading:3:1)
    at Module._compile (module.js:541:32)
    at Object.Module._extensions..js (module.js:550:10)
    at Module.load (module.js:458:32)
    at tryModuleLoad (module.js:417:12)
    at Function.Module._load (module.js:409:3)
`

I am using Parabola GNU/Linux.

**Comment by dariox86** [comment]
As a quick 'n dirty fix, I have converted /usr/bin/argo-trading to Unix format and modified the file like this:

`#!/usr/bin/env node

require("/usr/lib/node_modules/argo-trading/src/server/app.js");`

Perhaps this is not the proper way, but it works though.

/usr/bin/argo-trading-standalone has the same problem with Windows newline and after fixing it, it still doesn't work.

**Comment by dariox86** [comment]
Another note: "$ npm install -g argo-trading" needs superuser privileges in order to execute. Perhaps the symbol should be changed from "$" to "#"?

**Comment by albertosantini** [comment]
Thanks a lot for the feedback. 

About end-of-line issue, it is fixed in the master: see #7. In a few weeks I will publish a new release. 

About the script itself, intending the required main file, I think it is correct, at least in my environment. 

About root privileges, it depends on your setup: I don't need one. 

At the moment I am out of town and I check it again when I come back. ;)

**Comment by dariox86** [comment]
Probably it is a problem with my setup. Feel free to close the issue. Thank you.

**Comment by albertosantini** [comment]
`v3.9.0` published.
