### ISSUE TITLE
REST Api not working for new OANDA Accounts 

### ISSUE THREAD

**Issue by nicola89bs** [albertosantini/argo#9]
Hi Alberto,
I'm trying to use Argo with a new Oanda account, but it returns 0 accounts. Looking at the documentation:

> Note: The REST API only has access to Legacy accounts. To access v20 accounts please use the v20 REST API.

([http://developer.oanda.com/rest-live/introduction/](http://developer.oanda.com/rest-live/introduction/))

Any chance that the code is going to be updated to make use of what they call "v20" API? 

Thanks!
Nicola

**Comment by albertosantini** [comment]
Thanks for the feedback.

When v20 REST API will be completed and released, I give a try with with it.

At the moment, for instance, streaming or pricing history is not implemented.
A `coming soon` message is displayed: http://developer.oanda.com/rest-live-v20/streaming-ep/
